// Generated by gencpp from file my_commander/action_commandFeedback.msg
// DO NOT EDIT!


#ifndef MY_COMMANDER_MESSAGE_ACTION_COMMANDFEEDBACK_H
#define MY_COMMANDER_MESSAGE_ACTION_COMMANDFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_commander
{
template <class ContainerAllocator>
struct action_commandFeedback_
{
  typedef action_commandFeedback_<ContainerAllocator> Type;

  action_commandFeedback_()
    : cmd_out(0.0)  {
    }
  action_commandFeedback_(const ContainerAllocator& _alloc)
    : cmd_out(0.0)  {
    }



   typedef double _cmd_out_type;
  _cmd_out_type cmd_out;




  typedef boost::shared_ptr< ::my_commander::action_commandFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_commander::action_commandFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct action_commandFeedback_

typedef ::my_commander::action_commandFeedback_<std::allocator<void> > action_commandFeedback;

typedef boost::shared_ptr< ::my_commander::action_commandFeedback > action_commandFeedbackPtr;
typedef boost::shared_ptr< ::my_commander::action_commandFeedback const> action_commandFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_commander::action_commandFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_commander::action_commandFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'my_commander': ['/home/tianshipei/ros_ws/devel/share/my_commander/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_commander::action_commandFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_commander::action_commandFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_commander::action_commandFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_commander::action_commandFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_commander::action_commandFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_commander::action_commandFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_commander::action_commandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f7410aaefb32aa45c708beeb052f064";
  }

  static const char* value(const ::my_commander::action_commandFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f7410aaefb32aa4ULL;
  static const uint64_t static_value2 = 0x5c708beeb052f064ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_commander::action_commandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_commander/action_commandFeedback";
  }

  static const char* value(const ::my_commander::action_commandFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_commander::action_commandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
float64 cmd_out\n\
\n\
";
  }

  static const char* value(const ::my_commander::action_commandFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_commander::action_commandFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct action_commandFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_commander::action_commandFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_commander::action_commandFeedback_<ContainerAllocator>& v)
  {
    s << indent << "cmd_out: ";
    Printer<double>::stream(s, indent + "  ", v.cmd_out);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_COMMANDER_MESSAGE_ACTION_COMMANDFEEDBACK_H
