// Generated by gencpp from file my_commander/action_commandGoal.msg
// DO NOT EDIT!


#ifndef MY_COMMANDER_MESSAGE_ACTION_COMMANDGOAL_H
#define MY_COMMANDER_MESSAGE_ACTION_COMMANDGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_commander
{
template <class ContainerAllocator>
struct action_commandGoal_
{
  typedef action_commandGoal_<ContainerAllocator> Type;

  action_commandGoal_()
    : start(false)
    , amplitude(0.0)
    , frequency(0.0)  {
    }
  action_commandGoal_(const ContainerAllocator& _alloc)
    : start(false)
    , amplitude(0.0)
    , frequency(0.0)  {
    }



   typedef uint8_t _start_type;
  _start_type start;

   typedef double _amplitude_type;
  _amplitude_type amplitude;

   typedef double _frequency_type;
  _frequency_type frequency;




  typedef boost::shared_ptr< ::my_commander::action_commandGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_commander::action_commandGoal_<ContainerAllocator> const> ConstPtr;

}; // struct action_commandGoal_

typedef ::my_commander::action_commandGoal_<std::allocator<void> > action_commandGoal;

typedef boost::shared_ptr< ::my_commander::action_commandGoal > action_commandGoalPtr;
typedef boost::shared_ptr< ::my_commander::action_commandGoal const> action_commandGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_commander::action_commandGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_commander::action_commandGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'my_commander': ['/home/tianshipei/ros_ws/devel/share/my_commander/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_commander::action_commandGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_commander::action_commandGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_commander::action_commandGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_commander::action_commandGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_commander::action_commandGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_commander::action_commandGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_commander::action_commandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "052e3b1c760a0b55150a984e9cb579f6";
  }

  static const char* value(const ::my_commander::action_commandGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x052e3b1c760a0b55ULL;
  static const uint64_t static_value2 = 0x150a984e9cb579f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_commander::action_commandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_commander/action_commandGoal";
  }

  static const char* value(const ::my_commander::action_commandGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_commander::action_commandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool start\n\
float64 amplitude\n\
float64 frequency\n\
";
  }

  static const char* value(const ::my_commander::action_commandGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_commander::action_commandGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.amplitude);
      stream.next(m.frequency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct action_commandGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_commander::action_commandGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_commander::action_commandGoal_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
    s << indent << "amplitude: ";
    Printer<double>::stream(s, indent + "  ", v.amplitude);
    s << indent << "frequency: ";
    Printer<double>::stream(s, indent + "  ", v.frequency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_COMMANDER_MESSAGE_ACTION_COMMANDGOAL_H
