// Generated by gencpp from file my_commander/commandResult.msg
// DO NOT EDIT!


#ifndef MY_COMMANDER_MESSAGE_COMMANDRESULT_H
#define MY_COMMANDER_MESSAGE_COMMANDRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_commander
{
template <class ContainerAllocator>
struct commandResult_
{
  typedef commandResult_<ContainerAllocator> Type;

  commandResult_()
    : total_cycle(0)  {
    }
  commandResult_(const ContainerAllocator& _alloc)
    : total_cycle(0)  {
    }



   typedef uint32_t _total_cycle_type;
  _total_cycle_type total_cycle;




  typedef boost::shared_ptr< ::my_commander::commandResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_commander::commandResult_<ContainerAllocator> const> ConstPtr;

}; // struct commandResult_

typedef ::my_commander::commandResult_<std::allocator<void> > commandResult;

typedef boost::shared_ptr< ::my_commander::commandResult > commandResultPtr;
typedef boost::shared_ptr< ::my_commander::commandResult const> commandResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_commander::commandResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_commander::commandResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'my_commander': ['/home/tianshipei/ros_ws/devel/share/my_commander/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_commander::commandResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_commander::commandResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_commander::commandResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_commander::commandResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_commander::commandResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_commander::commandResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_commander::commandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8986217f8ac4d0f052704a88fb12ed7d";
  }

  static const char* value(const ::my_commander::commandResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8986217f8ac4d0f0ULL;
  static const uint64_t static_value2 = 0x52704a88fb12ed7dULL;
};

template<class ContainerAllocator>
struct DataType< ::my_commander::commandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_commander/commandResult";
  }

  static const char* value(const ::my_commander::commandResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_commander::commandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Result messages\n\
uint32 total_cycle	#numbers of cycles have been run when terminated\n\
";
  }

  static const char* value(const ::my_commander::commandResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_commander::commandResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_cycle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct commandResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_commander::commandResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_commander::commandResult_<ContainerAllocator>& v)
  {
    s << indent << "total_cycle: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_cycle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_COMMANDER_MESSAGE_COMMANDRESULT_H
