// Generated by gencpp from file my_commander/interface_cmd.msg
// DO NOT EDIT!


#ifndef MY_COMMANDER_MESSAGE_INTERFACE_CMD_H
#define MY_COMMANDER_MESSAGE_INTERFACE_CMD_H

#include <ros/service_traits.h>


#include <my_commander/interface_cmdRequest.h>
#include <my_commander/interface_cmdResponse.h>


namespace my_commander
{

struct interface_cmd
{

typedef interface_cmdRequest Request;
typedef interface_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct interface_cmd
} // namespace my_commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_commander::interface_cmd > {
  static const char* value()
  {
    return "ece6299263d227b65ea798b52ee8ac88";
  }

  static const char* value(const ::my_commander::interface_cmd&) { return value(); }
};

template<>
struct DataType< ::my_commander::interface_cmd > {
  static const char* value()
  {
    return "my_commander/interface_cmd";
  }

  static const char* value(const ::my_commander::interface_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::my_commander::interface_cmdRequest> should match 
// service_traits::MD5Sum< ::my_commander::interface_cmd > 
template<>
struct MD5Sum< ::my_commander::interface_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_commander::interface_cmd >::value();
  }
  static const char* value(const ::my_commander::interface_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_commander::interface_cmdRequest> should match 
// service_traits::DataType< ::my_commander::interface_cmd > 
template<>
struct DataType< ::my_commander::interface_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::my_commander::interface_cmd >::value();
  }
  static const char* value(const ::my_commander::interface_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_commander::interface_cmdResponse> should match 
// service_traits::MD5Sum< ::my_commander::interface_cmd > 
template<>
struct MD5Sum< ::my_commander::interface_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_commander::interface_cmd >::value();
  }
  static const char* value(const ::my_commander::interface_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_commander::interface_cmdResponse> should match 
// service_traits::DataType< ::my_commander::interface_cmd > 
template<>
struct DataType< ::my_commander::interface_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::my_commander::interface_cmd >::value();
  }
  static const char* value(const ::my_commander::interface_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_COMMANDER_MESSAGE_INTERFACE_CMD_H
