// Generated by gencpp from file example_srv/simple_float_service_message.msg
// DO NOT EDIT!


#ifndef EXAMPLE_SRV_MESSAGE_SIMPLE_FLOAT_SERVICE_MESSAGE_H
#define EXAMPLE_SRV_MESSAGE_SIMPLE_FLOAT_SERVICE_MESSAGE_H

#include <ros/service_traits.h>


#include <example_srv/simple_float_service_messageRequest.h>
#include <example_srv/simple_float_service_messageResponse.h>


namespace example_srv
{

struct simple_float_service_message
{

typedef simple_float_service_messageRequest Request;
typedef simple_float_service_messageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simple_float_service_message
} // namespace example_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::example_srv::simple_float_service_message > {
  static const char* value()
  {
    return "977b20eb68513f2dcfa12a9673ec2ddd";
  }

  static const char* value(const ::example_srv::simple_float_service_message&) { return value(); }
};

template<>
struct DataType< ::example_srv::simple_float_service_message > {
  static const char* value()
  {
    return "example_srv/simple_float_service_message";
  }

  static const char* value(const ::example_srv::simple_float_service_message&) { return value(); }
};


// service_traits::MD5Sum< ::example_srv::simple_float_service_messageRequest> should match 
// service_traits::MD5Sum< ::example_srv::simple_float_service_message > 
template<>
struct MD5Sum< ::example_srv::simple_float_service_messageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::example_srv::simple_float_service_message >::value();
  }
  static const char* value(const ::example_srv::simple_float_service_messageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::example_srv::simple_float_service_messageRequest> should match 
// service_traits::DataType< ::example_srv::simple_float_service_message > 
template<>
struct DataType< ::example_srv::simple_float_service_messageRequest>
{
  static const char* value()
  {
    return DataType< ::example_srv::simple_float_service_message >::value();
  }
  static const char* value(const ::example_srv::simple_float_service_messageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::example_srv::simple_float_service_messageResponse> should match 
// service_traits::MD5Sum< ::example_srv::simple_float_service_message > 
template<>
struct MD5Sum< ::example_srv::simple_float_service_messageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::example_srv::simple_float_service_message >::value();
  }
  static const char* value(const ::example_srv::simple_float_service_messageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::example_srv::simple_float_service_messageResponse> should match 
// service_traits::DataType< ::example_srv::simple_float_service_message > 
template<>
struct DataType< ::example_srv::simple_float_service_messageResponse>
{
  static const char* value()
  {
    return DataType< ::example_srv::simple_float_service_message >::value();
  }
  static const char* value(const ::example_srv::simple_float_service_messageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXAMPLE_SRV_MESSAGE_SIMPLE_FLOAT_SERVICE_MESSAGE_H
