; Auto-generated. Do not edit!


(cl:in-package baxter_traj_streamer-msg)


;//! \htmlinclude trajGoal.msg.html

(cl:defclass <trajGoal> (roslisp-msg-protocol:ros-message)
  ((trajectory
    :reader trajectory
    :initarg :trajectory
    :type trajectory_msgs-msg:JointTrajectory
    :initform (cl:make-instance 'trajectory_msgs-msg:JointTrajectory))
   (traj_id
    :reader traj_id
    :initarg :traj_id
    :type cl:integer
    :initform 0))
)

(cl:defclass trajGoal (<trajGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <trajGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'trajGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name baxter_traj_streamer-msg:<trajGoal> is deprecated: use baxter_traj_streamer-msg:trajGoal instead.")))

(cl:ensure-generic-function 'trajectory-val :lambda-list '(m))
(cl:defmethod trajectory-val ((m <trajGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader baxter_traj_streamer-msg:trajectory-val is deprecated.  Use baxter_traj_streamer-msg:trajectory instead.")
  (trajectory m))

(cl:ensure-generic-function 'traj_id-val :lambda-list '(m))
(cl:defmethod traj_id-val ((m <trajGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader baxter_traj_streamer-msg:traj_id-val is deprecated.  Use baxter_traj_streamer-msg:traj_id instead.")
  (traj_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <trajGoal>) ostream)
  "Serializes a message object of type '<trajGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'trajectory) ostream)
  (cl:let* ((signed (cl:slot-value msg 'traj_id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <trajGoal>) istream)
  "Deserializes a message object of type '<trajGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'trajectory) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'traj_id) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<trajGoal>)))
  "Returns string type for a message object of type '<trajGoal>"
  "baxter_traj_streamer/trajGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'trajGoal)))
  "Returns string type for a message object of type 'trajGoal"
  "baxter_traj_streamer/trajGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<trajGoal>)))
  "Returns md5sum for a message object of type '<trajGoal>"
  "795a47f183c47120e2bd82737a4d2a43")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'trajGoal)))
  "Returns md5sum for a message object of type 'trajGoal"
  "795a47f183c47120e2bd82737a4d2a43")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<trajGoal>)))
  "Returns full string definition for message of type '<trajGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%#the lines with the hash signs are merely comments~%#goal, result and feedback are defined by this fixed order, and separated by 3 hyphens~%trajectory_msgs/JointTrajectory trajectory~%int32 traj_id~%~%================================================================================~%MSG: trajectory_msgs/JointTrajectory~%Header header~%string[] joint_names~%JointTrajectoryPoint[] points~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: trajectory_msgs/JointTrajectoryPoint~%# Each trajectory point specifies either positions[, velocities[, accelerations]]~%# or positions[, effort] for the trajectory to be executed.~%# All specified values are in the same order as the joint names in JointTrajectory.msg~%~%float64[] positions~%float64[] velocities~%float64[] accelerations~%float64[] effort~%duration time_from_start~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'trajGoal)))
  "Returns full string definition for message of type 'trajGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%#the lines with the hash signs are merely comments~%#goal, result and feedback are defined by this fixed order, and separated by 3 hyphens~%trajectory_msgs/JointTrajectory trajectory~%int32 traj_id~%~%================================================================================~%MSG: trajectory_msgs/JointTrajectory~%Header header~%string[] joint_names~%JointTrajectoryPoint[] points~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: trajectory_msgs/JointTrajectoryPoint~%# Each trajectory point specifies either positions[, velocities[, accelerations]]~%# or positions[, effort] for the trajectory to be executed.~%# All specified values are in the same order as the joint names in JointTrajectory.msg~%~%float64[] positions~%float64[] velocities~%float64[] accelerations~%float64[] effort~%duration time_from_start~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <trajGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'trajectory))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <trajGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'trajGoal
    (cl:cons ':trajectory (trajectory msg))
    (cl:cons ':traj_id (traj_id msg))
))
