// Generated by gencpp from file cartesian_moves/cartTrajFeedback.msg
// DO NOT EDIT!


#ifndef CARTESIAN_MOVES_MESSAGE_CARTTRAJFEEDBACK_H
#define CARTESIAN_MOVES_MESSAGE_CARTTRAJFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cartesian_moves
{
template <class ContainerAllocator>
struct cartTrajFeedback_
{
  typedef cartTrajFeedback_<ContainerAllocator> Type;

  cartTrajFeedback_()
    : fdbk(0)  {
    }
  cartTrajFeedback_(const ContainerAllocator& _alloc)
    : fdbk(0)  {
    }



   typedef int32_t _fdbk_type;
  _fdbk_type fdbk;




  typedef boost::shared_ptr< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct cartTrajFeedback_

typedef ::cartesian_moves::cartTrajFeedback_<std::allocator<void> > cartTrajFeedback;

typedef boost::shared_ptr< ::cartesian_moves::cartTrajFeedback > cartTrajFeedbackPtr;
typedef boost::shared_ptr< ::cartesian_moves::cartTrajFeedback const> cartTrajFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cartesian_moves

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'cartesian_moves': ['/home/tianshipei/ros_ws/devel/share/cartesian_moves/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46cc8f8da6ebf35aedc6bad2e96b2e59";
  }

  static const char* value(const ::cartesian_moves::cartTrajFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46cc8f8da6ebf35aULL;
  static const uint64_t static_value2 = 0xedc6bad2e96b2e59ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartesian_moves/cartTrajFeedback";
  }

  static const char* value(const ::cartesian_moves::cartTrajFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback: optional; could declare step number of trajectory in progress\n\
int32 fdbk\n\
\n\
";
  }

  static const char* value(const ::cartesian_moves::cartTrajFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fdbk);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cartTrajFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartesian_moves::cartTrajFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartesian_moves::cartTrajFeedback_<ContainerAllocator>& v)
  {
    s << indent << "fdbk: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fdbk);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTESIAN_MOVES_MESSAGE_CARTTRAJFEEDBACK_H
