(cl:defpackage robot_simulator-msg
  (:use )
  (:export
   "<TRAJMSGRESULT>"
   "TRAJMSGRESULT"
   "<TRAJMSGFEEDBACK>"
   "TRAJMSGFEEDBACK"
   "<TRAJMSGGOAL>"
   "TRAJMSGGOAL"
   "<TRAJMSGACTIONFEEDBACK>"
   "TRAJMSGACTIONFEEDBACK"
   "<TRAJMSGACTIONGOAL>"
   "TRAJMSGACTIONGOAL"
   "<TRAJMSGACTION>"
   "TRAJMSGACTION"
   "<TRAJMSGACTIONRESULT>"
   "TRAJMSGACTIONRESULT"
  ))

