; Auto-generated. Do not edit!


(cl:in-package robot_simulator-msg)


;//! \htmlinclude TrajMsgFeedback.msg.html

(cl:defclass <TrajMsgFeedback> (roslisp-msg-protocol:ros-message)
  ((cmd_out
    :reader cmd_out
    :initarg :cmd_out
    :type cl:float
    :initform 0.0))
)

(cl:defclass TrajMsgFeedback (<TrajMsgFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TrajMsgFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TrajMsgFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_simulator-msg:<TrajMsgFeedback> is deprecated: use robot_simulator-msg:TrajMsgFeedback instead.")))

(cl:ensure-generic-function 'cmd_out-val :lambda-list '(m))
(cl:defmethod cmd_out-val ((m <TrajMsgFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_simulator-msg:cmd_out-val is deprecated.  Use robot_simulator-msg:cmd_out instead.")
  (cmd_out m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TrajMsgFeedback>) ostream)
  "Serializes a message object of type '<TrajMsgFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'cmd_out))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TrajMsgFeedback>) istream)
  "Deserializes a message object of type '<TrajMsgFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'cmd_out) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TrajMsgFeedback>)))
  "Returns string type for a message object of type '<TrajMsgFeedback>"
  "robot_simulator/TrajMsgFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TrajMsgFeedback)))
  "Returns string type for a message object of type 'TrajMsgFeedback"
  "robot_simulator/TrajMsgFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TrajMsgFeedback>)))
  "Returns md5sum for a message object of type '<TrajMsgFeedback>"
  "0f7410aaefb32aa45c708beeb052f064")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TrajMsgFeedback)))
  "Returns md5sum for a message object of type 'TrajMsgFeedback"
  "0f7410aaefb32aa45c708beeb052f064")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TrajMsgFeedback>)))
  "Returns full string definition for message of type '<TrajMsgFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Feedback messages~%float64 cmd_out		#current output~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TrajMsgFeedback)))
  "Returns full string definition for message of type 'TrajMsgFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Feedback messages~%float64 cmd_out		#current output~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TrajMsgFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TrajMsgFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TrajMsgFeedback
    (cl:cons ':cmd_out (cmd_out msg))
))
