; Auto-generated. Do not edit!


(cl:in-package robot_simulator-msg)


;//! \htmlinclude TrajMsgResult.msg.html

(cl:defclass <TrajMsgResult> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:float
    :initform 0.0))
)

(cl:defclass TrajMsgResult (<TrajMsgResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TrajMsgResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TrajMsgResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_simulator-msg:<TrajMsgResult> is deprecated: use robot_simulator-msg:TrajMsgResult instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <TrajMsgResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_simulator-msg:progress-val is deprecated.  Use robot_simulator-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TrajMsgResult>) ostream)
  "Serializes a message object of type '<TrajMsgResult>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'progress))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TrajMsgResult>) istream)
  "Deserializes a message object of type '<TrajMsgResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'progress) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TrajMsgResult>)))
  "Returns string type for a message object of type '<TrajMsgResult>"
  "robot_simulator/TrajMsgResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TrajMsgResult)))
  "Returns string type for a message object of type 'TrajMsgResult"
  "robot_simulator/TrajMsgResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TrajMsgResult>)))
  "Returns md5sum for a message object of type '<TrajMsgResult>"
  "7afca0099e0cddc25243b1e3569895fe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TrajMsgResult)))
  "Returns md5sum for a message object of type 'TrajMsgResult"
  "7afca0099e0cddc25243b1e3569895fe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TrajMsgResult>)))
  "Returns full string definition for message of type '<TrajMsgResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result messages~%float64 progress	#current rate of progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TrajMsgResult)))
  "Returns full string definition for message of type 'TrajMsgResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result messages~%float64 progress	#current rate of progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TrajMsgResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TrajMsgResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TrajMsgResult
    (cl:cons ':progress (progress msg))
))
