(cl:defpackage cartesian_moves-msg
  (:use )
  (:export
   "<CARTTRAJFEEDBACK>"
   "CARTTRAJFEEDBACK"
   "<CARTTRAJACTIONGOAL>"
   "CARTTRAJACTIONGOAL"
   "<CARTTRAJRESULT>"
   "CARTTRAJRESULT"
   "<CARTTRAJACTION>"
   "CARTTRAJACTION"
   "<CARTTRAJACTIONRESULT>"
   "CARTTRAJACTIONRESULT"
   "<CARTTRAJGOAL>"
   "CARTTRAJGOAL"
   "<CARTTRAJACTIONFEEDBACK>"
   "CARTTRAJACTIONFEEDBACK"
  ))

