; Auto-generated. Do not edit!


(cl:in-package cartesian_moves-msg)


;//! \htmlinclude cartTrajFeedback.msg.html

(cl:defclass <cartTrajFeedback> (roslisp-msg-protocol:ros-message)
  ((fdbk
    :reader fdbk
    :initarg :fdbk
    :type cl:integer
    :initform 0))
)

(cl:defclass cartTrajFeedback (<cartTrajFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <cartTrajFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'cartTrajFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cartesian_moves-msg:<cartTrajFeedback> is deprecated: use cartesian_moves-msg:cartTrajFeedback instead.")))

(cl:ensure-generic-function 'fdbk-val :lambda-list '(m))
(cl:defmethod fdbk-val ((m <cartTrajFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cartesian_moves-msg:fdbk-val is deprecated.  Use cartesian_moves-msg:fdbk instead.")
  (fdbk m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <cartTrajFeedback>) ostream)
  "Serializes a message object of type '<cartTrajFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'fdbk)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <cartTrajFeedback>) istream)
  "Deserializes a message object of type '<cartTrajFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'fdbk) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<cartTrajFeedback>)))
  "Returns string type for a message object of type '<cartTrajFeedback>"
  "cartesian_moves/cartTrajFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'cartTrajFeedback)))
  "Returns string type for a message object of type 'cartTrajFeedback"
  "cartesian_moves/cartTrajFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<cartTrajFeedback>)))
  "Returns md5sum for a message object of type '<cartTrajFeedback>"
  "46cc8f8da6ebf35aedc6bad2e96b2e59")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'cartTrajFeedback)))
  "Returns md5sum for a message object of type 'cartTrajFeedback"
  "46cc8f8da6ebf35aedc6bad2e96b2e59")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<cartTrajFeedback>)))
  "Returns full string definition for message of type '<cartTrajFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback: optional; could declare step number of trajectory in progress~%int32 fdbk~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'cartTrajFeedback)))
  "Returns full string definition for message of type 'cartTrajFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback: optional; could declare step number of trajectory in progress~%int32 fdbk~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <cartTrajFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <cartTrajFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'cartTrajFeedback
    (cl:cons ':fdbk (fdbk msg))
))
