(cl:defpackage my_commander-msg
  (:use )
  (:export
   "<COMMANDACTION>"
   "COMMANDACTION"
   "<COMMANDRESULT>"
   "COMMANDRESULT"
   "<COMMANDACTIONRESULT>"
   "COMMANDACTIONRESULT"
   "<COMMANDACTIONFEEDBACK>"
   "COMMANDACTIONFEEDBACK"
   "<COMMANDGOAL>"
   "COMMANDGOAL"
   "<COMMANDACTIONGOAL>"
   "COMMANDACTIONGOAL"
   "<COMMANDFEEDBACK>"
   "COMMANDFEEDBACK"
  ))

