; Auto-generated. Do not edit!


(cl:in-package my_commander-msg)


;//! \htmlinclude action_commandResult.msg.html

(cl:defclass <action_commandResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass action_commandResult (<action_commandResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <action_commandResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'action_commandResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_commander-msg:<action_commandResult> is deprecated: use my_commander-msg:action_commandResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <action_commandResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_commander-msg:success-val is deprecated.  Use my_commander-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <action_commandResult>) ostream)
  "Serializes a message object of type '<action_commandResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <action_commandResult>) istream)
  "Deserializes a message object of type '<action_commandResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<action_commandResult>)))
  "Returns string type for a message object of type '<action_commandResult>"
  "my_commander/action_commandResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'action_commandResult)))
  "Returns string type for a message object of type 'action_commandResult"
  "my_commander/action_commandResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<action_commandResult>)))
  "Returns md5sum for a message object of type '<action_commandResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'action_commandResult)))
  "Returns md5sum for a message object of type 'action_commandResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<action_commandResult>)))
  "Returns full string definition for message of type '<action_commandResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'action_commandResult)))
  "Returns full string definition for message of type 'action_commandResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <action_commandResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <action_commandResult>))
  "Converts a ROS message object to a list"
  (cl:list 'action_commandResult
    (cl:cons ':success (success msg))
))
