; Auto-generated. Do not edit!


(cl:in-package my_commander-msg)


;//! \htmlinclude commandResult.msg.html

(cl:defclass <commandResult> (roslisp-msg-protocol:ros-message)
  ((total_cycle
    :reader total_cycle
    :initarg :total_cycle
    :type cl:integer
    :initform 0))
)

(cl:defclass commandResult (<commandResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <commandResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'commandResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_commander-msg:<commandResult> is deprecated: use my_commander-msg:commandResult instead.")))

(cl:ensure-generic-function 'total_cycle-val :lambda-list '(m))
(cl:defmethod total_cycle-val ((m <commandResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_commander-msg:total_cycle-val is deprecated.  Use my_commander-msg:total_cycle instead.")
  (total_cycle m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <commandResult>) ostream)
  "Serializes a message object of type '<commandResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_cycle)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_cycle)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_cycle)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_cycle)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <commandResult>) istream)
  "Deserializes a message object of type '<commandResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_cycle)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_cycle)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_cycle)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_cycle)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<commandResult>)))
  "Returns string type for a message object of type '<commandResult>"
  "my_commander/commandResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'commandResult)))
  "Returns string type for a message object of type 'commandResult"
  "my_commander/commandResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<commandResult>)))
  "Returns md5sum for a message object of type '<commandResult>"
  "8986217f8ac4d0f052704a88fb12ed7d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'commandResult)))
  "Returns md5sum for a message object of type 'commandResult"
  "8986217f8ac4d0f052704a88fb12ed7d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<commandResult>)))
  "Returns full string definition for message of type '<commandResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result messages~%uint32 total_cycle	#numbers of cycles have been run when terminated~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'commandResult)))
  "Returns full string definition for message of type 'commandResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result messages~%uint32 total_cycle	#numbers of cycles have been run when terminated~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <commandResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <commandResult>))
  "Converts a ROS message object to a list"
  (cl:list 'commandResult
    (cl:cons ':total_cycle (total_cycle msg))
))
