// Generated by gencpp from file baxter_traj_streamer/trajGoal.msg
// DO NOT EDIT!


#ifndef BAXTER_TRAJ_STREAMER_MESSAGE_TRAJGOAL_H
#define BAXTER_TRAJ_STREAMER_MESSAGE_TRAJGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace baxter_traj_streamer
{
template <class ContainerAllocator>
struct trajGoal_
{
  typedef trajGoal_<ContainerAllocator> Type;

  trajGoal_()
    : trajectory()
    , traj_id(0)  {
    }
  trajGoal_(const ContainerAllocator& _alloc)
    : trajectory(_alloc)
    , traj_id(0)  {
    }



   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;

   typedef int32_t _traj_id_type;
  _traj_id_type traj_id;




  typedef boost::shared_ptr< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> const> ConstPtr;

}; // struct trajGoal_

typedef ::baxter_traj_streamer::trajGoal_<std::allocator<void> > trajGoal;

typedef boost::shared_ptr< ::baxter_traj_streamer::trajGoal > trajGoalPtr;
typedef boost::shared_ptr< ::baxter_traj_streamer::trajGoal const> trajGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_traj_streamer::trajGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_traj_streamer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'baxter_traj_streamer': ['/home/tianshipei/ros_ws/devel/share/baxter_traj_streamer/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "795a47f183c47120e2bd82737a4d2a43";
  }

  static const char* value(const ::baxter_traj_streamer::trajGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x795a47f183c47120ULL;
  static const uint64_t static_value2 = 0xe2bd82737a4d2a43ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_traj_streamer/trajGoal";
  }

  static const char* value(const ::baxter_traj_streamer::trajGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
#the lines with the hash signs are merely comments\n\
#goal, result and feedback are defined by this fixed order, and separated by 3 hyphens\n\
trajectory_msgs/JointTrajectory trajectory\n\
int32 traj_id\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectory\n\
Header header\n\
string[] joint_names\n\
JointTrajectoryPoint[] points\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectoryPoint\n\
# Each trajectory point specifies either positions[, velocities[, accelerations]]\n\
# or positions[, effort] for the trajectory to be executed.\n\
# All specified values are in the same order as the joint names in JointTrajectory.msg\n\
\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] effort\n\
duration time_from_start\n\
";
  }

  static const char* value(const ::baxter_traj_streamer::trajGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectory);
      stream.next(m.traj_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct trajGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_traj_streamer::trajGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_traj_streamer::trajGoal_<ContainerAllocator>& v)
  {
    s << indent << "trajectory: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
    s << indent << "traj_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.traj_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_TRAJ_STREAMER_MESSAGE_TRAJGOAL_H
