// Generated by gencpp from file baxter_traj_streamer/trajResult.msg
// DO NOT EDIT!


#ifndef BAXTER_TRAJ_STREAMER_MESSAGE_TRAJRESULT_H
#define BAXTER_TRAJ_STREAMER_MESSAGE_TRAJRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_traj_streamer
{
template <class ContainerAllocator>
struct trajResult_
{
  typedef trajResult_<ContainerAllocator> Type;

  trajResult_()
    : return_val(0)
    , traj_id(0)  {
    }
  trajResult_(const ContainerAllocator& _alloc)
    : return_val(0)
    , traj_id(0)  {
    }



   typedef int32_t _return_val_type;
  _return_val_type return_val;

   typedef int32_t _traj_id_type;
  _traj_id_type traj_id;




  typedef boost::shared_ptr< ::baxter_traj_streamer::trajResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_traj_streamer::trajResult_<ContainerAllocator> const> ConstPtr;

}; // struct trajResult_

typedef ::baxter_traj_streamer::trajResult_<std::allocator<void> > trajResult;

typedef boost::shared_ptr< ::baxter_traj_streamer::trajResult > trajResultPtr;
typedef boost::shared_ptr< ::baxter_traj_streamer::trajResult const> trajResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_traj_streamer::trajResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_traj_streamer::trajResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_traj_streamer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'baxter_traj_streamer': ['/home/tianshipei/ros_ws/devel/share/baxter_traj_streamer/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_traj_streamer::trajResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_traj_streamer::trajResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_traj_streamer::trajResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_traj_streamer::trajResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_traj_streamer::trajResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_traj_streamer::trajResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_traj_streamer::trajResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7db3918b810c71ba21e4940e794cf96";
  }

  static const char* value(const ::baxter_traj_streamer::trajResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7db3918b810c71bULL;
  static const uint64_t static_value2 = 0xa21e4940e794cf96ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_traj_streamer::trajResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_traj_streamer/trajResult";
  }

  static const char* value(const ::baxter_traj_streamer::trajResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_traj_streamer::trajResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
#return_val = 1 for traj complete; traj_id should echo the input traj_id\n\
int32 return_val\n\
int32 traj_id\n\
";
  }

  static const char* value(const ::baxter_traj_streamer::trajResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_traj_streamer::trajResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return_val);
      stream.next(m.traj_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct trajResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_traj_streamer::trajResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_traj_streamer::trajResult_<ContainerAllocator>& v)
  {
    s << indent << "return_val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.return_val);
    s << indent << "traj_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.traj_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_TRAJ_STREAMER_MESSAGE_TRAJRESULT_H
